version: "3"

networks:
  laravel:

services:

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - laravel

  php:
    build: ./src
    restart: always
    expose:
      - "9000"
    links:
      - mysql
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - laravel
  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
        - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel